# Generated by Django 4.0.1 on 2022-07-27 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('max_marks', models.FloatField()),
                ('content', models.TextField(max_length=1000)),
                ('assignment', models.FileField(blank=True, upload_to='assignments')),
                ('due_date', models.DateTimeField()),
                ('contribution', models.FloatField()),
                ('publish_grades', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('icon', models.ImageField(upload_to='course_icons')),
                ('name', models.CharField(max_length=255)),
                ('slot', models.CharField(max_length=1)),
                ('credits', models.FloatField()),
                ('credit_structure', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=100)),
                ('course_intro', models.FileField(upload_to='course_intro')),
                ('publish_grades', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=255)),
                ('name', models.CharField(max_length=150)),
                ('userType', models.CharField(choices=[('Student', 'Student'), ('Faculty', 'Faculty'), ('Admin', 'Admin')], max_length=10)),
                ('image', models.ImageField(default='profile_pictures/default.png', upload_to='profile_pictures')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.FileField(upload_to='submissions')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='SemesterLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('courses', models.ManyToManyField(to='Users.Course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField(max_length=2000)),
                ('message_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_from', to='Users.profile')),
                ('message_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_to', to='Users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.FloatField()),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='CourseGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('A', 'A'), ('A-', 'A-'), ('B', 'B'), ('B-', 'B-'), ('C', 'C'), ('C-', 'C-'), ('D', 'D')], max_length=2)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.profile')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='coordinators',
            field=models.ManyToManyField(related_name='course_coordinator', to='Users.Profile'),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisite',
            field=models.ManyToManyField(blank=True, to='Users.Course'),
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(related_name='course_students', to='Users.Profile'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.course'),
        ),
    ]
