# Generated by Django 4.0.1 on 2022-07-27 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='coordinators',
        ),
        migrations.AddField(
            model_name='course',
            name='coordinators',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='course_coordinator', to='Users.profile'),
            preserve_default=False,
        ),
    ]
