# Generated by Django 4.0.1 on 2022-07-28 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_submission_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='prerequisite',
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisite',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='Users.course'),
            preserve_default=False,
        ),
    ]
