# Generated by Django 4.0.1 on 2022-07-28 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_remove_course_prerequisite_course_prerequisite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='prerequisite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.course'),
        ),
    ]
