# Generated by Django 4.0.1 on 2022-07-28 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_alter_course_prerequisite'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='semester_code',
            field=models.CharField(default=2101, max_length=10),
            preserve_default=False,
        ),
    ]
