from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('dashboard', views.dashboard, name='dashboard'),
    path('announcements', views.announcements, name='announcements'),
    path('announcements/<str:code>', views.announcement, name='announcements'),
    path('courses', views.courses, name='courses'),
    path('courses/past', views.past_courses, name='past_courses'),
    path('courses/<str:code>', views.course, name='course'),
    path('courses/<str:code>/material', views.material, name='material'),
    path('courses/<str:code>/participants', views.participants, name='participants'),
    path('manage/<str:course>', views.manage_course, name='manage_course'),
    path('manage/<str:course>/announcements', views.manage_announcements, name='manage_announcements'),
    path('manage/<str:course>/announcements/add', views.add_announcement, name='add_announcement'),
    path('manage/<str:course>/announcements/<str:pk>/edit', views.edit_announcement, name='edit_announcement'),
    path('manage/<str:course>/announcements/<str:pk>/delete', views.delete_announcement, name='delete_announcement'),
    path('manage/<str:course>/materials', views.manage_materials, name='manage_materials'),
    path('manage/<str:course>/materials/add', views.add_material, name='add_material'),
    path('manage/<str:course>/materials/<str:pk>/delete', views.delete_material, name='delete_material'),
    path('manage/<str:course>/assignments', views.manage_assignments, name='manage_assignments'),
    path('manage/<str:course>/assignments/add', views.add_assignment, name='add_assignment'),
    path('manage/<str:course>/assignments/<str:pk>/edit', views.edit_assignment, name='edit_assignment'),
    path('manage/<str:course>/assignments/<str:pk>/delete', views.delete_assignment, name='delete_assignment'),
    path('manage/<str:course>/participants', views.manage_participants, name='manage_participants'),
    path('manage/<str:course>/submissions', views.manage_submissions, name='manage_submissions'),
    path('manage/<str:course>/submissions/<str:pk>', views.upload_submissions, name='upload_submissions'),
    path('manage/<str:course>/submissions/<str:pk>/<str:username>', views.save_submissions, name='save_submissions'),
    path('manage/<str:course>/grades', views.manage_grades, name='manage_grades'),
    path('manage/<str:course>/grades/<str:username>/edit', views.edit_grades, name='edit_grades'),
    path('grades', views.grades, name='grades'),
    path('grades/<str:code>', views.course_grades, name='course_grades'),
    path('assignments', views.assignments, name='assignments'),
    path('assignments/<str:code>', views.course_assignments, name='course_assignments'),
    path('assignments/<str:code>/<str:name>', views.assignment, name='assignment'),
    path('messages', views.messages, name='messages'),
    path('messages/<str:user>', views.message, name='message'),
    path('settings', views.settings, name='settings'),
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
    path('api/dashboard_resources/', views.dashboard_resources, name='dashboard_resources'),
    path('api/send_message/', views.send_message, name='send_message'),
    path('api/get_messages/', views.get_messages, name='get_messages'),
]